services:
  server:
    build: .
    network_mode: "host"
    volumes:
      - "./account_db.db3:/home/mani/rtype/account_db.db3:Z"
      - "./account_db.db3-shm:/home/mani/rtype/account_db.db3-shm:Z"
      - "./account_db.db3-wal:/home/mani/rtype/account_db.db3-wal:Z"
      - "./server/config.cfg:/home/mani/rtype/server/config.cfg:Z"
      - "./rtype.cfg:/home/mani/rtype/rtype.cfg:Z"
    restart: always
