name: a

on:
  push:
    tags:
      - 'B*.*.*'
    branches:
      - dev
      - main
jobs:
  push-on-main:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - run: git push origin dev:main
  create-a-releases:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Compile
        run: make
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            r-type_server
            r-type_client
