name: ci

on:
  push:
    tags:
      - 'B*.*.*'
    branches:
      - dev
      - main
      - ci
      - ci-test
jobs:
  push-on-main:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: git push origin HEAD:refs/heads/ci-test
  # create-a-releases:
  #   needs: push-on-main
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   container: epitechcontent/epitest-docker
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Compile
  #       run: make
  #     - name: Create Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         name: ${{ github.ref_name }}
  #         files: |
  #           r-type_server
  #           r-type_client
