name: ci

on:
  push:
    tags:
      - 'B*.*.*'
    branches:
      - dev
      - main
jobs:
  push-on-main:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - run: git push origin dev:main
  create-a-releases:
    needs: push-on-main
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Compile
        run: make
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          files: |
            r-type_server
            r-type_client
