name: deployment

on:
  push:
    tags:
      - 'v*.*.*'
      - 'B*.*.*'
    branches:
      - dev
jobs:
  create-a-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
        contents: write
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: make
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          files: |
            r-type_server
            r-type_client
  push-on-main:
    needs: create-a-release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: git push origin HEAD:refs/heads/main --force
